#!/usr/bin/perl

use strict; 
use warnings;


open GD, '<', '/root/acctlist';
my @acctlist = (<GD>);
foreach my $acct (@acctlist) {print "$acct";}

foreach (@acctlist) {
   chomp;
   print "$_.restore.log\n";
   open RLOG, '<', "/root/$_.restore.log" or warn "Cannot open $_.restore.log: $!\n";
   while (<RLOG>) {
      chomp;
      if (/time stamp/) {
         print "$&\n" if m#\.(\/\w+\.?\w+)+#;
      }
   }
}
